[manager]
# Expand on https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
prepend_keymap = [
	# Seeking
	{ on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "<C-d>", run = "seek 5",  desc = "Seek down 5 units in the preview" },
]
append_keymap = [
	{ on = "<C-p>", run = "arrow -1", desc = "Move cursor up" },
	{ on = "<C-n>", run = "arrow 1",  desc = "Move cursor down" },
]
